# Generated by Django 4.0.4 on 2022-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_slug', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLS',
            },
        ),
    ]
